version: '3.7'

services:
  website:
     build:
        context: .
        dockerfile: Dockerfile_website
     volumes:
        - ./flask_instance:/flask_instance
        - ./scrapies:/scrapies
        - ./flask_instance:/scrapies/genscrap/genscrap/flask_instance
        - ./webpack/public:/searchfront/static:ro
     ports:
        - '8000:8000'
     # dash means to stdout
     #--capture-output
     #--enable-stdio-inheritance
     command: python searchfront/app.py
     env_file:
        - '.env'

  worker:
     build:
        context: .
        dockerfile: Dockerfile_website
     volumes:
        - ./flask_instance:/searchfront/flask_instance
    # The command should read the config and the task list entry from celeryconfig.py
    # 
    # -B enables celery beat, from docs: "is is convenient if you’ll never run more than one worker
    # node, but it’s not commonly used and for that reason isn’t recommended for production use"
    # (but will do for now)
     command: celery worker -B -E -l critical
     env_file:
        - ".env"

  omnivore:
     build:
        context: .
        dockerfile: Dockerfile_omnivore
     volumes:
        # Persist quicklisp in a named volume.
        - quicklisp:/root/quicklisp:Z
        - ./lisp-startup:/lisp/startup
        - ./textviews:/lisp/textviews
        - ./omnivore:/lisp/omnivore
     ports:
        # Map the original 4242 to 4243.
        - '4243:4242'
        # Expose Swank.
        - '4006:4005'
     command: 'sbcl --load /lisp/startup/lisp-startup-omnivore.lisp'
     # Make sbcl not exit immediately.
     tty: true

  speechtractor:
     build:
        context: .
        dockerfile: Dockerfile_stractor
     volumes:
        # Persist quicklisp in a named volume.
        - quicklisp:/root/quicklisp:Z
        - ./lisp-startup:/lisp/startup
        - ./speechtractor:/lisp/speechtractor
     ports:
        - '3757:3756'
        # Expose Swank.
        - '4007:4005'
     command: 'sbcl --load /lisp/startup/lisp-startup-stractor.lisp'
     # Make sbcl not exit immediately.
     tty: true

  postgres:
     image: 'postgres:12.2'
     volumes:
        - pgdata:/var/lib/postgresql/data:Z
     ports:
        # Map the original 5432 to 5433.
        - '5433:5432'
     env_file:
        - '.env'

  redis:
    image: 'redis:6.0-rc'
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - redisdata:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6380:6379'

  solr:
     build:
        context: .
        dockerfile: Dockerfile_solr
     ports:
        # Map the original 8983 to 8984.
        - '8984:8983'
     volumes:
        # Kinda the documentation's suggestion to persist data.
        # A named volume is kept persistent by Docker behind the scenes.
        # (Z should facilitate living with SELinux?)
        - solrdata:/var/solr/:Z
        # Allow posting to Solr documents we've prepared with scripts.
        - ./processing-scripts:/processing-scripts

# Named volumes.
volumes:
   pgdata:
   quicklisp:
   redisdata:
   solrdata:
