version: '3.7'

services:
  postgres:
     image: 'postgres:12.2'
     volumes:
        - pgdata:/var/lib/postgresql/data:Z
     ports:
        # Map the original 5432 to 5433.
        - '5433:5432'
     env_file:
        - '.env'

  website:
     build:
        context: .
        dockerfile: Dockerfile_website
     volumes:
        - ./flask_instance:/searchfront/flask_instance
        - ./scrapies:/searchfront/scrapies
        - ./flask_instance:/scrapies/genscrap/genscrap/flask_instance
        - ./webpack/public:/searchfront/searchfront/static:ro
     ports:
        - '8000:8000'
     # dash means to stdout
     #--capture-output
     #--enable-stdio-inheritance
     command: >
        gunicorn -b 0.0.0.0:8000
        --log-level=debug
        --access-logfile -
        --error-logfile -
        --reload
        "searchfront.app:create_app()"
     env_file:
        - '.env'

  omnivore:
     build:
        context: .
        dockerfile: Dockerfile_omnivore
     volumes:
        # Persist quicklisp in a named volume.
        - quicklisp:/root/quicklisp:Z
        - ./lisp-startup:/lisp/startup
        - ./textviews:/lisp/textviews
        - ./omnivore:/lisp/omnivore
     ports:
        # Map the original 4242 to 4243.
        - '4243:4242'
        # Expose Swank.
        - '4006:4005'
     command: 'sbcl --load /lisp/startup/lisp-startup-omnivore.lisp'
     # Make sbcl not exit immediately.
     tty: true

  speechtractor:
     build:
        context: .
        dockerfile: Dockerfile_stractor
     volumes:
        # Persist quicklisp in a named volume.
        - quicklisp:/root/quicklisp:Z
        - ./lisp-startup:/lisp/startup
        - ./speechtractor:/lisp/speechtractor
     ports:
        - '3757:3756'
        # Expose Swank.
        - '4007:4005'
     command: 'sbcl --load /lisp/startup/lisp-startup-stractor.lisp'
     # Make sbcl not exit immediately.
     tty: true

  solr:
     build:
        context: .
        dockerfile: Dockerfile_solr
     ports:
        # Map the original 8983 to 8984.
        - '8984:8983'
     volumes:
        # Kinda the documentation's suggestion to persist data.
        # A named volume is kept persistent by Docker behind the scenes.
        # (Z should facilitate living with SELinux?)
        - solrdata:/var/solr/:Z
        # Allow posting to Solr documents we've prepared with scripts.
        - ./processing-scripts:/processing-scripts

# Named volumes.
volumes:
   pgdata:
   quicklisp:
   solrdata:
