FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -qq -y \
  build-essential libpq-dev --no-install-recommends

COPY requirements.txt requirements.txt
COPY setup.py setup.py
RUN pip install -r requirements.txt

COPY pytest.ini pytest.ini
COPY celeryconfig.py celeryconfig.py

COPY scrapies scrapies

RUN pip install --editable .

WORKDIR /
