version: '3.7'

services:
  website:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_website
     ports:
        - '127.0.0.1:8000:8000'
     # Use -v2 for more reporting
     command: daphne -b 0.0.0.0 -p 8000 -v3 ascan.asgi:application
     env_file:
        - '.env'
     depends_on:
        - postgres
        - redis
        - solr
     volumes:
        # lets us persist migrations and change templates without restarting
        - ./python_modules/ascan/:/opt/ascan/ascan/

  maintenance:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_website
     command: python3 maintenance.py -L WARNING
     env_file:
        - '.env'
     # This should restart on crashes.
     ###restart: unless-stopped
     depends_on:
        - website # to get the DB initialization

  zookeeper:
     image: zookeeper
     restart: unless-stopped
     volumes:
        - ./zoo.cfg:/conf/zoo.cfg

  nimbus:
     image: storm
     command: "storm admin remove_corrupt_topologies ; storm nimbus"
     restart: unless-stopped
     ports:
       - 6628:6627
     env_file:
        - '.env'
     tty: true
     depends_on:
        - omnivore2
        - postgres
        - redis
        - solr
        - selenium
        - website
        - zookeeper

  storm_supervisor:
     image: storm
     command: storm supervisor
     restart: unless-stopped
     tty: true
     depends_on:
       - nimbus # to lead us
       - zookeeper # to register

###-  stormcrawler:
###-     build:
###-        context: .
###-        dockerfile: dockerfiles/Dockerfile_stormcrawler
###-        args:
###-          UAGENT_STRING: ${UAGENT_STRING}
###-     # We run it in local mode, not to deal with Zookeeper.
###-     command: storm jar generalcrawl-0.1.jar com.actualscan.crawling.CrawlTopology
###-     env_file:
###-        - '.env'
###-          #restart: unless-stopped # Storm local mode dies every 30 secs
###-     tty: true
###-     depends_on:
###-        - nimbus

  redditscrape:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_redditscrape
     command: python reddit_scraper.py -L INFO
     env_file:
        - '.env'
     depends_on:
        - postgres
        - solr
        - website
        - omnivore2

  speechtractor:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_stractor
     ports:
        - '127.0.0.1:3757:3756'
     command: "sbcl --eval '(ql:quickload :speechtractor)'"
     # Make sbcl not exit immediately.
     tty: true
     env_file:
        - '.env'
     depends_on:
        - solr

  omnivore2:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_omnivore2
     ports:
        - '127.0.0.1:6824:6823'
     # Only authenticate with the client certificate for now.
     command: >-
       gunicorn -b 0.0.0.0:6823 wsgi:app
       --ssl-version TLSv1_2
       --keyfile /home/certs/ascan_internal_key.key
       --certfile /home/certs/ascan_internal.pem
       --ca-certs /home/certs/ascan_internal.pem
     env_file:
        - '.env'
     depends_on:
        - redis
        - solr

  postgres:
     image: 'postgres:12.2'
     volumes:
        - pgdata:/var/lib/postgresql/data:Z
     ports:
        # Map the original 5432 to 5433.
        - '127.0.0.1:5433:5432'
     env_file:
        - '.env'

  selenium:
     image: 'selenium/standalone-chrome:3.141.59'
     volumes:
        - /dev/shm:/dev/shm
     ports:
        - '127.0.0.1:4444:4444'
     env_file:
        - '.env'

  # Needed for Django Channels (and Celery when we use it).
  redis:
     build:
       context: .
       dockerfile: dockerfiles/Dockerfile_redis
     command: >-
       redis-server /usr/local/etc/redis/redis.conf
       --tls-port 6379 --port 0
       --tls-cert-file /home/certs/ascan_internal.pem
       --tls-key-file /home/certs/ascan_internal_key.key
       --tls-ca-cert-file /home/certs/ascan_internal.pem
     volumes:
       - redisdata:/var/lib/redis/data
       - ./redis.conf:/usr/local/etc/redis/redis.conf
     ports:
       - '127.0.0.1:6380:6379'

  solr:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_solr
        args:
          KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
          SOLR_ADMIN_HASH: ${SOLR_ADMIN_HASH}
          SOLR_UPDATER_HASH: ${SOLR_UPDATER_HASH}
          SOLR_READER_HASH: ${SOLR_READER_HASH}
     ports:
        # Map the original 8983 to 8984.
        - '127.0.0.1:8984:8983'
     volumes:
        - solrdata:/var/solr/:Z

# Named volumes.
volumes:
   pgdata:
   redisdata:
   solrdata:
