version: '3.7'

services:
  website:
     build:
        context: .
        dockerfile: Dockerfile_website
     volumes:
        - flask_instance:/flask_instance:Z
     ports:
        - '8000:8000'
     command: >
        gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "searchfront.app:create_app()"

  omnivore:
     build:
        context: .
        dockerfile: Dockerfile_omnivore
     volumes:
        # Persist quicklisp in a named volume.
        - quicklisp:/root/quicklisp:Z
        - ./lisp-startup:/lisp/startup
        - ./textviews:/lisp/textviews
        - ./omnivore:/lisp/omnivore
     ports:
        # Map the original 4242 to 2424.
        - '2424:4242'
        # Expose Swank.
        - '4005:4005'
     command: 'sbcl --load /lisp/startup/lisp-startup.lisp'
     # Make sbcl not exit immediately.
     tty: true

  solr:
     build:
        context: .
        dockerfile: Dockerfile_solr
     ports:
        # Map the original 8983 to 8984.
        - '8984:8983'
     stop_grace_period: 30s
     volumes:
        # Kinda the documentation's suggestion to persist data.
        # A named volume is kept persistent by Docker behind the scenes.
        # (Z should facilitate living with SELinux?)
        - solrdata:/var/solr/:Z
        # Allow posting to Solr documents we've prepared with scripts.
        - ./processing-scripts:/processing-scripts

# Named volumes.
volumes:
   flask_instance:
   quicklisp:
   solrdata:
