version: '3.7'

services:
  website:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_website
     ports:
        - '127.0.0.1:8000:8000'
     # Use -v2 for more reporting
     command: daphne -b 0.0.0.0 -p 8000 -v1 ascan.asgi:application
     env_file:
        - '.env'
     depends_on:
        - postgres
        - solr
     volumes:
        # lets us persist migrations and change templates without restarting
        - ./python_modules/ascan/:/opt/ascan/ascan/

  maintenance:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_website
     command: python3 maintenance.py -L WARNING
     env_file:
        - '.env'
     # This should restart on crashes.
     restart: unless-stopped
     depends_on:
        - website # to get the DB initialization

  scrapy:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_scrapy
     command: scrapy crawl general -L WARNING
     env_file:
        - '.env'
     depends_on:
        - postgres
        - solr
        - redis
        - selenium
        - website
        - omnivore2
     volumes:
        - ./pagecopies:/scrapies/pagecopies

  redditscrape:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_redditscrape
     command: python reddit_scraper.py -L INFO
     env_file:
        - '.env'
     depends_on:
        - postgres
        - solr
        - website
        - omnivore2

  speechtractor:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_stractor
     ports:
        - '127.0.0.1:3757:3756'
     command: "sbcl --eval '(ql:quickload :speechtractor)'"
     # Make sbcl not exit immediately.
     tty: true
     depends_on:
        - solr

  omnivore2:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_omnivore2
     ports:
        - '127.0.0.1:6824:6823'
     command: "gunicorn -b 0.0.0.0:6823 wsgi:app"
     env_file:
        - '.env'
     depends_on:
        - solr

  postgres:
     image: 'postgres:12.2'
     volumes:
        - pgdata:/var/lib/postgresql/data:Z
     ports:
        # Map the original 5432 to 5433.
        - '127.0.0.1:5433:5432'
     env_file:
        - '.env'

  selenium:
     image: 'selenium/standalone-chrome:3.141.59'
     volumes:
        - /dev/shm:/dev/shm
     ports:
        - '127.0.0.1:4444:4444'
     env_file:
        - '.env'

   # Needed for Django Channels (and Celery when we use it).
  redis:
    image: 'redis:6.0-rc'
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - redisdata:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '127.0.0.1:6380:6379'

  solr:
     build:
        context: .
        dockerfile: dockerfiles/Dockerfile_solr
     ports:
        # Map the original 8983 to 8984.
        - '127.0.0.1:8984:8983'
     volumes:
        - solrdata:/var/solr/:Z

# Named volumes.
volumes:
   pgdata:
   redisdata:
   solrdata:
