FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -qq -y \
  build-essential libpq-dev --no-install-recommends

ENV INSTALL_PATH /searchfront
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

COPY requirements.txt requirements.txt
COPY setup.py setup.py
RUN pip install -r requirements.txt

COPY flask_config flask_config
COPY pytest.ini pytest.ini
COPY celeryconfig.py celeryconfig.py

COPY searchfront searchfront

RUN pip install --editable .

WORKDIR /
