
FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -qq -y \
  build-essential libpq-dev libssl-dev --no-install-recommends

WORKDIR /

COPY requirements.scrapy.txt requirements.txt
COPY setup.py setup.py
RUN pip install -r requirements.txt

COPY pytest.ini pytest.ini
COPY ascan /ascan
COPY py_common /py_common
RUN pip install --editable .

COPY scrapping/scrapy scrapy
WORKDIR /scrapy
