FROM redis:6.0-rc

USER root
WORKDIR /home/certs/
COPY certs/dev/ascan_dev_internal.pem /home/certs/ascan_internal.pem
COPY certs/dev/ascan_dev_internal_key.key /home/certs/ascan_internal_key.key
RUN chown -R redis:redis /home/certs/

WORKDIR /data
