FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -qq -y \
  build-essential libpq-dev libssl-dev --no-install-recommends

WORKDIR /home/certs/
COPY certs/dev/ascan_dev_internal.pem /home/certs/ascan_internal.pem
COPY certs/dev/ascan_dev_internal_key.key /home/certs/ascan_internal_key.key

WORKDIR /opt/omnivore2
COPY python_modules/omnivore2/requirements.txt /opt/omnivore2/

RUN pip install -r requirements.txt
RUN python -m spacy download en_core_web_sm

COPY python_modules/omnivore2/ /opt/omnivore2/
