FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -qq -y \
  build-essential curl libpq-dev libssl-dev sbcl --no-install-recommends

WORKDIR /

COPY requirements.website.txt requirements.txt
COPY setup.py setup.py
RUN pip install -r requirements.txt

# Install and populate quicklisp.
WORKDIR /tmp
RUN curl -O https://beta.quicklisp.org/quicklisp.lisp
RUN echo "(load \"quicklisp.lisp\") (quicklisp-quickstart:install :path \"/opt/quicklisp\") (ql::without-prompting (ql:add-to-init-file))" | sbcl
COPY lisp/textviews /opt/quicklisp/local-projects/
COPY lisp/omnivore /opt/quicklisp/local-projects/
# Loading the package should download the dependencies, try to keep this in Docker build cache
RUN sbcl --eval '(ql:quickload :omnivore)' --eval '(sb-ext:quit)'

WORKDIR /
COPY ascan /ascan
COPY py_common /ascan/py_common
RUN pip install --editable .

WORKDIR /ascan
COPY lisp/lisp-startup-omnivore.lisp .
COPY testing/ascan/* ./
COPY pytest.ini pytest.ini
