FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -y curl libssl-dev sbcl

# Install and populate quicklisp.
WORKDIR /tmp
RUN curl -O https://beta.quicklisp.org/quicklisp.lisp
RUN echo "(load \"quicklisp.lisp\") (quicklisp-quickstart:install :path \"/opt/quicklisp\") (ql::without-prompting (ql:add-to-init-file))" | sbcl

WORKDIR /home/certs/
COPY certs/dev/ascan_dev_internal.pem /home/certs/ascan_internal.pem
COPY certs/dev/ascan_dev_internal_key.key /home/certs/ascan_internal_key.key

COPY lisp/speechtractor /opt/quicklisp/local-projects/
# Loading the package should download the dependencies, try to keep this in Docker build cache
RUN sbcl --eval '(ql:quickload :speechtractor)' --eval '(sb-ext:quit)'
