
FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -qq -y \
  build-essential libpq-dev libssl-dev --no-install-recommends

WORKDIR /

COPY requirements.scrapy.txt requirements.txt
RUN pip install -r requirements.txt

COPY ascan /ascan
COPY py_common /ascan/py_common
WORKDIR /ascan
COPY setup.py setup.py
RUN pip install --editable .

# Rename the dir to avoid name collisions
COPY scrapping/scrapy /scrapping
WORKDIR /scrapping
RUN pip install --editable .
COPY testing/scrapping/scrapy/* ./
COPY pytest.ini pytest.ini
