
FROM python:3.7.5-slim-buster

RUN apt-get update && apt-get install -qq -y \
  build-essential libpq-dev libssl-dev --no-install-recommends

WORKDIR /opt/ascan

COPY python_modules/requirements.scrapy.txt requirements.txt
RUN pip install -r requirements.txt

COPY python_modules/ascan ascan
WORKDIR /opt/ascan/ascan
RUN pip install --editable .

WORKDIR /opt/ascan
COPY python_modules/ascan_scrapy ascan_scrapy
WORKDIR /opt/ascan/ascan_scrapy
