- hosts: stractor
  tags: stractor
  remote_user: "{{ ascan_hosts_user_name }}"
  vars_files:
     - ../vars/main.yml
  vars:
     ansistrano_deploy_from: ../lisp/speechtractor
     ansistrano_deploy_to: /root/ascan_lisp/speechtractor
     ansistrano_version_dir: "releases" # Releases folder name
     ansistrano_current_dir: "current" # Softlink name.
     ansistrano_current_via: "symlink"
     ansistrano_keep_releases: 2
     ansistrano_deploy_via: "rsync"
     ansistrano_allow_anonymous_stats: no
  handlers:
     - import_tasks: ../handlers/main.yml
  become: yes
  environment:
     # make sure we can find installed sbcl
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  tasks:
     - name: make sure rsync is installed
       dnf:
          name: rsync
          state: present
     - include_role:
        name: ansistrano.deploy
     - name: ensure symlinking the recent speechtractor release to quicklisp local-projects
       file:
          src: "/root/lisp/speechtractor/current"
          dest: "/opt/quicklisp/local-projects/speechtractor"
          state: link
     - name: make sure the speechtractor service is running
       systemd:
          name: speechtractor
          state: started
          enabled: yes
          daemon_reload: yes
